#!/bin/sh

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
# 
# Copyright (c) 2005 Vino Fernando Crescini  <jcrescin@cit.uws.edu.au>

progname="speaktime"
progver="1.0"
def_snd_dir=/usr/local/share/speaktime

unset thetimeis
unset snd_dir
unset playlist

while [ ${#} -ge 1 ]; do
  if [ "${1}" = "-h" ]; then
    echo "usage:       ${progname} [options]"
    echo "options:"
    echo "  -h         print this usage and exit"
    echo "  -t         say \"the time is\" (off)"
    echo "  -d dir     directory containing mp3 files (/usr/local/share/speaktime)"
    echo "  -v         print version and exit"
    echo ""
    exit 0
  elif [ "${1}" = "-t" ]; then
    thetimeis="1"
  elif [ "${1}" = "-d" ]; then
    if [ -n "${2}" ]; then
      snd_dir="${2}"
      shift 1
    fi
  elif [ "${1}" = "-v" ]; then
    echo "${progname} ${progver}"
    exit 0
  else
    echo "unrecognised option ${1}"
    exit -1
  fi
  shift 1
done

if [ -z "${snd_dir}" ]; then
  snd_dir=${def_snd_dir}
fi

if [ "${thetimeis}" = "1" ]; then
  playlist="${snd_dir}/thetimeis.mp3"
fi

# get time
curr_hour=`date | awk {'print $4'} | cut -d":" -f1`
curr_min=`date | awk {'print $4'} | cut -d":" -f2`

# do the hour
hour=$[${curr_hour} % 12]
if [ ${hour} -eq 0 ]; then
  playlist="${playlist} ${snd_dir}/12.mp3"
elif [ ${hour} -ge 10 ]; then
  playlist="${playlist} ${snd_dir}/${hour}.mp3"
else
  playlist="${playlist} ${snd_dir}/0${hour}.mp3"
fi

# do the minutes
if [ ${curr_min} -ge 10 ] && [ ${curr_min} -le 19 ]; then
  playlist="${playlist} ${snd_dir}/${curr_min}.mp3"
elif [ ${curr_min} -gt 0 ]; then
  if [ ${curr_min} -ge 1 ] && [ ${curr_min} -le 9 ]; then
    playlist="${playlist} ${snd_dir}/oh.mp3"
  else
    playlist="${playlist} ${snd_dir}/${curr_min%[0-9]}0.mp3"
  fi
  if [ $[curr_min % 10] -ne 0 ]; then
    playlist="${playlist} ${snd_dir}/0${curr_min#[0-9]}.mp3"
  fi
fi

# am or pm ?
if [ ${curr_hour} -lt 12 ]; then
  playlist="${playlist} ${snd_dir}/am.mp3"
else
  playlist="${playlist} ${snd_dir}/pm.mp3"
fi

mpg123 -q ${playlist}
