#!/bin/sh
# The contents of this file are subject to the Mozilla Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.mozilla.org/MPL/
#
# Software distributed under the License is distributed on an "AS
# IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
# implied. See the License for the specific language governing
# rights and limitations under the License.
#
# The Original Code is Goanna.
#
# The Initial Developer of the Original Code is Tuxia
# Labs PTY LTD.  Portions created by Tuxia Labs 
# PTY LTD are Copyright (C) 2001 Tuxia Labs PTY LTD. All
# Rights Reserved.
#
# Contributor(s):
#   Vino Crescini <vino.crescini@tuxia.com>


if [ ${#} -ne 2 ]
then
  echo "Usage: GoannaGtkEmbedBrowserCreateComp <component dir> <file prefix>"
  echo "Files will be copied to <prefix>/goanna"
  exit 1
fi

compdir=${1}
prefix=${2}

mycompname="nanozilla/gtkembedbrowser"

# assume symlink to goanna is back one dir.
sourcedir=../goanna/dist/bin
targetdir=${compdir}/${mycompname}/files/${prefix}/goanna

mkdir -p ${targetdir}
for i in `cat ./GoannaGtkEmbedBrowserFiles`
do
  if [ -d ${sourcedir}/${i} ]
  then
    mkdir -p ${targetdir}/${i}
  else
    cp ${sourcedir}/${i} ${targetdir}/${i}
  fi
done

# copy the readme file(s), if any
targetcompdir=${compdir}/${mycompname}
for i in ./README.*
do
  if [ -r "${i}" ]
  then
    cp ${i} ${targetcompdir}
  fi
done

# copy the wrapper script
if [ -r ../goanna-embed ]
then
  cp ../goanna-embed ${targetdir}
fi
