#!/bin/sh

# Vino Fernando Crescini  <jcrescin@cit.uws.edu.au>
# 24 Nov 2004

CONFIG_FILE=/etc/wireless.conf

if ! [ -r ${CONFIG_FILE} ]; then
  exit 0
fi

if [ ${#} != "2" ]; then
  echo "usage: ${0} <interface> <profile>"
  exit -1
fi

. ${CONFIG_FILE}

# make sure the interface is up
ifconfig ${1} up || exit ${?}
sleep 1

# now make sure the interface is wireless
if ! grep ${1}: /proc/net/wireless > /dev/null 2>&1; then
  echo "${1} not a wireless interface" 1>&2
  exit -2
fi

# set wireless params
if [ -n "${ESSID[$2]}" ]; then
  echo "essid:   ${ESSID[$2]}"
  iwconfig ${1} essid ${ESSID[$2]} || exit ${?}
fi
if [ -n "${MODE[$2]}" ]; then
  echo "mode:    ${MODE[$2]}"
  iwconfig ${1} mode ${MODE[$2]} || exit ${?}
fi
if [ -n "${KEY[$2]}" ]; then
  echo "key:     **********"
  iwconfig ${1} key ${KEY[$2]} || exit ${?}
fi
if [ -n "${CHANNEL[$2]}" ]; then
  echo "channel: ${CHANNEL[$2]}"
  iwconfig ${1} channel ${CHANNEL[$2]} || exit ${?}
fi

# now for the interface params
if [ ${USE_DHCP[$2]} = "yes" ]; then
  # if USE_DHCP is set, ignore everything else
  dhcpcd -d -t 30 ${1} || exit ${?}
else
  # manually set params
  ifconfig ${1} ${IPADDR[$2]} netmask ${NETMASK[$2]} || exit ${?}
  echo "ipaddr:  ${IPADDR[$2]}"
  echo "netmask: ${NETMASK[$2]}"
fi

exit 0
