#!/bin/sh

# Vino Fernando Crescini  <jcrescin@cit.uws.edu.au>
# 2005-02-03

while read i j k; do 
  j=$[$j / 1024 ]
  k=mb
  echo -n "$i"
  x=`echo $i | wc -c`
  while [ $x -le 16 ]; do
    echo -ne " "
    x=$[$x + 1]
  done
  x=`echo $j | wc -c`
  while [ $x -lt 7 ]; do
    echo -ne " "
    x=$[$x + 1]
  done
  echo $j $k
done < /proc/meminfo
