#!/bin/sh
# Vino Crescini
# Started: 2002 Aug 11
# Updated: 2003 Jun 02

if [ ${#} = "1" ] && [ ${1} = "-v" ]; then
  VERBOSE=1
fi

# modified
cvs diff --brief 2>&1 | grep "Index:" | cut -d ' ' -f 2 | ( [ -n "${VERBOSE}" ] && while read i; do echo "M ${i}"; done || cat )

# added
cvs diff --brief 2>&1 | grep "is a new entry," | cut -d ' ' -f 3 | ( [ -n "${VERBOSE}" ] && while read i; do echo "A ${i}"; done || cat )

# removed
cvs diff --brief 2>&1 | grep "was removed," | cut -d ' ' -f 3 | ( [ -n "${VERBOSE}" ] && while read i; do echo "R ${i}"; done || cat )
