#!/bin/sh
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GNU CC; see the file COPYING.  If not, write to
# the Free Software Foundation, 59 Temple Place - Suite 330,
# Boston, MA 02111-1307, USA.
#
# Copyright (C) 2002-2003 Vino Fernando Crescini
#
# Vino Fernando Crescini  <jcrescin@cit.uws.edu.au>
# Started: 2002 Aug 11
# Updated: 2003 Dec 01 

unset VERBOSE

while [ ${#} -ge 1 ]; do
  if [ ${1} = "-v" ]; then
    VERBOSE="1"
  fi
  if [ ${1} = "-h" ]; then
    echo "$0 [-h|-v]"
    exit 0
  fi
  shift 1
done

# modified
cvs diff --brief 2>&1 | grep "Index:" | cut -d ' ' -f 2 | ( [ -n "${VERBOSE}" ] && while read i; do echo "M ${i}"; done || cat )

# added
cvs diff --brief 2>&1 | grep "is a new entry," | cut -d ' ' -f 3 | ( [ -n "${VERBOSE}" ] && while read i; do echo "A ${i}"; done || cat )

# removed
cvs diff --brief 2>&1 | grep "was removed," | cut -d ' ' -f 3 | ( [ -n "${VERBOSE}" ] && while read i; do echo "R ${i}"; done || cat )

exit 0
