#!/bin/bash

# Vino Crescini
# 2001 November 03

MPG123=`which mpg123`
ESDCAT=`which esdcat`

if ! [ -x ${MPG123} ]; then 
  echo "can't find mpg123"
  exit -1
fi

if ! [ -x ${ESDCAT} ]; then
  echo "can't find esdcat"
  exit -1
fi

if [ ${#} -ne 1 ]; then
  echo "usage ${0} <mp3-file>"
  exit -1
fi

if ! [ -r "${1}" ] || [ -z "`file -b \"${1}\" | grep MPEG | grep audio`" ]; then
  echo "invalid mp3 file"
  exit -1
fi

mpg123 -q -w - "${1}" | esdcat > /dev/null 2>&1

