#!/bin/sh

# mp3toau
# Vino Crescini
# 20 June 2001

mpgprog="/usr/local/bin/mpg123"
charlen=5
count=0

if ! [ ${#} = "1" ]
then
  echo "${0} <destination dir>"
  exit 0
fi

if ! [ -d ${1} ] || ! [ -w ${1} ]
then
  echo "${1} does not exist / not writable"
  exit 0
fi

if ! [ -x ${mpgprog} ]
then
  echo "can't find ${mpgprog}"
  exit 0
fi

for filename in *.mp3
do
  count=$[$count + 1]

  # pad name with zeroes
  name=${count}
  while [ `echo -n ${name} | wc -c` -lt ${charlen} ]
  do
    name=0${name}
  done
  
  echo "${filename} -> ${1}/${name}.au"
  ${mpgprog} -sq "${filename}" > ${1}/${name}.au
done
