#!/bin/sh

# mp3tocd
# Vino Crescini
# 26 June 2001

mpgprog="/usr/local/bin/mpg123"
cdrprog="/usr/bin/cdrecord"
mpgflags="--stereo -q"
cdrflags="-v speed=4 dev=0,00,00 -audio -nofix -swab -fs=8m -nopreemp"
cdrfixflags="-v dev=0,00,00 speed=4 -fix -eject"

if ! [ ${#} = "1" ]
then
  echo "${0} <mp3 dir>"
  exit 0
fi

if ! [ -d "${1}" ] || ! [ -r "${1}" ]
then
  echo "${1} does not exist / not readable"
  exit 0
fi

if ! [ -x ${mpgprog} ]
then
  echo "can't find ${mpgprog}"
  exit 0
fi

if ! [ -x ${cdrprog} ]
then
  echo "can't find ${cdrprog}"
  exit 0
fi

if [ `find "${1}" -maxdepth 1 -name "*.mp3" 2> /dev/null | wc -l` = "0" ]
then
  echo "can't find any mp3 files in ${1}"
  exit 0
fi

# decode and burn

find "${1}" -maxdepth 1 -name "*.mp3" 2> /dev/null | sort | while read filename
do
  echo "About to write $filename"
  ${mpgprog} ${mpgflags} -s "${filename}" | ${cdrprog} ${cdrflags} -
  echo "Finished writing $filename"
done

# fixate

${cdrprog} ${cdrfixflags}
