#!/bin/sh

# mp3toau
# Vino Crescini
# 20 June 2001

mpgprog="/usr/local/bin/mpg123"
count=0

if ! [ ${#} = "1" ]
then
  echo "${0} <destination dir>"
  exit 0
fi

if ! [ -d ${1} ] || ! [ -w ${1} ]
then
  echo "${1} does not exist / not writable"
  exit 0
fi

if ! [ -x ${mpgprog} ]
then
  echo "can't find ${mpgprog}"
  exit 0
fi

ls -1 *.mp3 | while read filename
do
  count=$[$count + 1]
  echo ${filename} -> ${1}/${count}.au
  ${mpgprog} -sq "${filename}" > ${1}/${count}.au
done
