#!/bin/sh

# publiciseTree
# Vino Crescini
# 11 June 2001

# recursive chmod and chown, treat files 
# and dirs differently

DIR_PERMISSION=775
FILE_PERMISSION=644
OWNER=root
GROUP=users

if [ ${#} = 1 ] 
then
  if [ -d ${1} ]
  then
    find ${1} | while read i
    do
      if [ -d "${i}" ]
      then
        chown ${OWNER}:${GROUP} "${i}"
        chmod ${DIR_PERMISSION} "${i}"
        echo dir : ${i}
      else
        chmod ${FILE_PERMISSION} "${i}"
        echo file : ${i}
      fi
    done
  fi
fi
