#!/bin/sh

# removeFile
# deletes files listed in $i
# Vino Crescini
# 18 June 2001

if ! [ $# = 1 ]; then
  exit 0;
fi

if ! [ -r $1 ]; then
  exit 0;
fi

cat $1 | while  read i;  do
  if [ -r $i ]; then
    echo rm $i
    rm -rf $i
  fi
done
