#!/bin/sh

# renameFiles
# Vino Crescini
# 11 June 2001

# rename all the files 
# in a directory to numbers

counter=1
charlen=5

mkdir /tmp/__tmp_$$_

for tempFile in *
do
  # get extension
  extension=${tempFile##*.}

  if [ ${extension} = ${tempFile} ]
  then
    # no extension so just drop the name
    extension=
  else
    extension=.${extension}
  fi

  # pad the name with zeroes
  name=${counter}
  while [ `echo -n ${name} | wc -c` -lt ${charlen} ]
  do
    name=0${name}
  done

  echo "renaming ${tempFile} to ${name}${extension}"

  mv ${tempFile} /tmp/__tmp_$$_/${name}${extension}

  counter=$[$counter+1]
done

mv /tmp/__tmp_$$_/* .
rmdir /tmp/__tmp_$$_
