#!/bin/sh

# renameFiles
# Vino Crescini
# 11 June 2001

# rename all the files 
# in a directory to numbers

counter=1

mkdir /tmp/__tmp_$$_

ls -1 | sort | while read tempFile
do
  # get extension
  extension=${tempFile##*.}

  if [ ${extension} = ${tempFile} ]
  then
    # no extension so just drop the name
    extension=
  else
    extension=.${extension}
  fi

  echo "renaming ${tempFile} to ${counter}${extension}"

  mv ${tempFile} /tmp/__tmp_$$_/${counter}${extension}

  counter=$[$counter+1]
done

mv /tmp/__tmp_$$_/* .
rmdir /tmp/__tmp_$$_
