#!/bin/sh

# renameFiles
# Vino Crescini
# 11 June 2001

# rename all the files 
# in a directory to numbers

counter=1
charlen=5
tempdir=./.tmp_$$_

if [ "${#}" = "1" ] && [ "${1}" = "-r" ]; then
  RECURSIVE=1
fi

mkdir $tempdir

for tempFile in *
do
  if [ "${RECURSIVE}" = "1" ] && [ -d "${tempFile}" ]; then
    cd "${tempFile}"
    echo entering `pwd`
    ${0} -r
    echo exiting `pwd`
    cd ..
  fi

  # get extension
  extension="${tempFile##*.}"

  if [ "${extension}" = "${tempFile}" ]
  then
    # no extension so just drop the name
    extension=
  else
    extension=".${extension}"
  fi

  # pad the name with zeroes
  name=${counter}
  while [ `echo -n ${name} | wc -c` -lt ${charlen} ]
  do
    name=0${name}
  done

  echo "renaming ${tempFile} to ${name}${extension}"

  mv "${tempFile}" $tempdir/${name}${extension}

  counter=$[$counter+1]
done

mv $tempdir/* .
rmdir $tempdir
