#!/bin/sh
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with GNU CC; see the file COPYING.  If not, write to
# the Free Software Foundation, 59 Temple Place - Suite 330,
# Boston, MA 02111-1307, USA.
# 
# Copyright (C) 2004 Vino Fernando Crescini  <jcrescin@cit.uws.edu.au>
#
 
# strip_cr - strip carriage return characters from files that came from
#            bloody windows users.

# 2004 Jun 01

infile="&0"
outfile="&1"

if [ ${#} -gt 2 ]; then
  echo "usage: strip_cr [input-file [output-file]]";
  exit -1
fi

if [ ${#} -ge 1 ] && [ "${1}" != "-" ]; then
  infile="${1}"
fi

if [ ${#} -eq 2 ] && [ "${2}" != "-" ]; then
  outfile="${2}"
fi

eval "sed -e \"s/
//\" <${infile} >${outfile}"
