#!/bin/sh

# stripsearch
# finds elves and strips them
# Vino Crescini
# 05 June 2001

for i in `find .`
do
  if [ -x ${i} ] && [ "`file ${i} | grep ELF`" ]
  then
    strip --strip-all ${i}
    strip --remove-section=.comment ${i}
    strip --remove-section=.note ${i}
    echo stripping ${i}
  fi 
done
