# Vino Crescini  <jcrescin@cit.uws.edu.au>

all : authorisation.dvi

clean :
	$(RM) authorisation.dvi authorisation.aux authorisation.toc

authorisation.dvi : authorisation.tex
	latex authorisation.tex
	latex authorisation.tex
